# Generated by Django 5.1.7 on 2025-03-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('picture', models.FileField(upload_to='uploads/cas')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Cas',
                'verbose_name_plural': 'cas',
            },
        ),
    ]
