# Generated by Django 5.1.7 on 2025-03-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cas',
            old_name='picture',
            new_name='picture_video',
        ),
    ]
